/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ZeroswapERC20 } from "./ZeroswapERC20";
export type { ZeroswapFactory } from "./ZeroswapFactory";
export type { ZeroswapPair } from "./ZeroswapPair";
export type { ZeroswapRouter } from "./ZeroswapRouter";
