/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWETH } from "./IWETH";
export type { IZeroswapCallee } from "./IZeroswapCallee";
export type { IZeroswapFactory } from "./IZeroswapFactory";
export type { IZeroswapPair } from "./IZeroswapPair";
export type { IZeroswapRouter } from "./IZeroswapRouter";
